# Generated by Django 4.2.6 on 2023-10-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Хештег',
                'verbose_name_plural': 'Хештеги',
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_et', models.DateTimeField(auto_created=True, null=True)),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Название телефона')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Загрузите фото или эмблему телефона')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Дайте описание')),
                ('type_mobil', models.CharField(choices=[('Красный', 'Красный'), ('Белый', 'Белый'), ('Синий', 'Синий'), ('Черный', 'Черный')], max_length=100, null=True, verbose_name='Выберите цвет телефона')),
                ('cost', models.PositiveIntegerField(null=True, verbose_name='Укажите цену')),
                ('director', models.CharField(max_length=100, null=True, verbose_name='В какой стране производиться')),
                ('number_of_page', models.IntegerField(null=True, verbose_name='Укажите колличество')),
                ('date_start', models.DateField(null=True, verbose_name='Укажите дату издания')),
                ('hashtag', models.ManyToManyField(to='mono.hashtag')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефон',
            },
        ),
    ]
