# Generated by Django 4.2.6 on 2023-11-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mono', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='Review',
            field=models.TextField(blank=True, null=True, verbose_name='Отзывы к продуктам'),
        ),
    ]
