# Generated by Django 4.2.6 on 2023-10-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mono', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
