# Generated by Django 4.2.6 on 2023-10-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mono', '0002_alter_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_et',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='number_of_page',
            field=models.IntegerField(null=True),
        ),
    ]
