# Generated by Django 4.2.6 on 2023-11-10 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mono', '0002_mobile_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='Review',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Отзывы к продуктам')),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mono.mobile')),
            ],
        ),
    ]
