# Generated by Django 4.2.6 on 2023-10-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mono', '0003_post_created_et_post_number_of_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Телефона', 'verbose_name_plural': 'Телефон'},
        ),
        migrations.AlterField(
            model_name='post',
            name='cost',
            field=models.PositiveIntegerField(null=True, verbose_name='Укажите цену'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Дайте описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='director',
            field=models.CharField(max_length=100, null=True, verbose_name='В какой стране производиться'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Загрузите фото или эмблему телефона'),
        ),
        migrations.AlterField(
            model_name='post',
            name='number_of_page',
            field=models.IntegerField(null=True, verbose_name='Укажите колличество'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Название телефона'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type_mobil',
            field=models.CharField(choices=[('Красный', 'Красный'), ('Белый', 'Белый'), ('Синий', 'Синий'), ('Черный', 'Черный')], max_length=100, null=True, verbose_name='Выберите цвет телефона'),
        ),
    ]
